#!/usr/bin/python3

import glob
import subprocess
import os.path
import re
import sys

# See
# http://www.jedisaber.com/eBooks/Tutorial.shtml

uuid = "whycryptocurrencies.com-0.1"

dirname = os.path.dirname(__file__)
site_dir = os.path.join(dirname, "_site")
ebook_files_dir = os.path.join(dirname, "ebook-files")

ebook_dir = os.path.join(dirname, "_ebook")
meta_dir = os.path.join(ebook_dir, "META-INF")
oebps_dir = os.path.join(ebook_dir, "OEBPS")
image_dir = os.path.join(oebps_dir, "images")

toc = [
    "eli5.html",
    "about_the_book.html",
    "acknowledgements.html",
    "how_to_use.html",
    "free.html",
    "about_me.html",
    "what_is_a_cryptocurrency.html",
    "properties_of_a_cryptocurrency.html",
    "how_do_cryptocurrencies_work.html",
    "look_out_for_snake_oil.html",
    "what_is_money.html",
    "are_cryptocurrencies_money.html",
    "better_digital_payments.html",
    "cheaper_faster.html",
    "undesirable_businesses.html",
    "freezing_of_merchant_accounts.html",
    "uncensorable_donations.html",
    "for_the_unbanked.html",
    "better_currency.html",
    "financial_crisis.html",
    "the_blind_leading_the_blind.html",
    "a_defective_system.html",
    "private_money.html",
    "global_currency.html",
    "brave_new_world.html",
    "darknet_markets.html",
    "swiss_bank_account_in_your_pocket.html",
    "cashless_dystopia.html",
    "protection_against_government_confiscation.html",
    "separation_of_money_and_state.html",
    "extensions.html",
    "timestamping_service.html",
    "uncensorable_twitter.html",
    "provably_fair_gambling.html",
    "tokens.html",
    "voting.html",
    "appendix.html",
    "bitcoin_whitepaper.html",
    "challenges.html",
    "cryptography.html",
]

titles = {
    "eli5.html": "Why cryptocurrencies in five minutes",
    "about_the_book.html": "About the book",
    "acknowledgements.html": "Acknowledgments",
    "how_to_use.html": "How to use this book",
    "free.html": "Completely free",
    "about_me.html": "About me, the author",
    "what_is_a_cryptocurrency.html": "What is a cryptocurrency?",
    "properties_of_a_cryptocurrency.html": "Properties of a cryptocurrency",
    "how_do_cryptocurrencies_work.html": "How do cryptocurrencies work?",
    "look_out_for_snake_oil.html": "Look out for snake oil",
    "what_is_money.html": "What is money?",
    "are_cryptocurrencies_money.html": "Are cryptocurrencies money?",
    "better_digital_payments.html": "Better digital payments",
    "cheaper_faster.html": "Cheaper & faster",
    "undesirable_businesses.html": "“Undesirable” businesses",
    "freezing_of_merchant_accounts.html": "Freezing of merchant accounts",
    "uncensorable_donations.html": "Uncensorable donations",
    "for_the_unbanked.html": "For the unbanked",
    "better_currency.html": "A better currency",
    "financial_crisis.html": "The financial crisis, bad loans and bailouts",
    "the_blind_leading_the_blind.html": "The blind leading the blind",
    "a_defective_system.html": "A defective system",
    "private_money.html": "Private money",
    "global_currency.html": "A global currency",
    "brave_new_world.html": "Brave new world",
    "darknet_markets.html": "Darknet markets",
    "swiss_bank_account_in_your_pocket.html": "A Swiss bank account in your pocket",
    "cashless_dystopia.html": "The cashless dystopia",
    "protection_against_government_confiscation.html": "Protection against government confiscation",
    "separation_of_money_and_state.html": "Separation of money and state",
    "extensions.html": "Extensions",
    "timestamping_service.html": "Timestamping service",
    "uncensorable_twitter.html": "Uncensorable Twitter",
    "provably_fair_gambling.html": "Provably fair gambling",
    "tokens.html": "Tokens",
    "voting.html": "Improved voting",
    "appendix.html": "Appendix",
    "bitcoin_whitepaper.html": "The Bitcoin white paper",
    "challenges.html": "Challenges for cryptocurrencies",
    "cryptography.html": "A hitchhiker’s guide to cryptography",
}

# {src: dst} of hrefs we need to replace
link_replace = {}

def main():
    clean()
    setup_basics()

    images = setup_images()

    setup_content_opf(images)
    setup_toc_ncx()
    setup_css()

    # FIXME Fonts:
    # https://www.oreilly.com/library/view/epub-3-best/9781449329129/ch04.html

    setup_post_replacements()
    setup_posts()

    create_zip()

    for link, new_link in link_replace.items():
        print(link, new_link)
    return

def clean():
    # Clean destination directory.
    subprocess.run(f"rm -r {ebook_dir}/", shell=True)
    subprocess.run(f"rm why_cryptocurrencies.epub", shell=True)

def setup_basics():
    # Create mimetype file
    subprocess.run(f"mkdir -p {ebook_dir}/", shell=True)
    with open(os.path.join(ebook_dir, "mimetype"), 'w') as f:
        f.write("application/epub+zip")

    # Create container
    subprocess.run(f"mkdir -p {meta_dir}", shell=True)
    subprocess.run(f"cp {ebook_files_dir}/container.xml {meta_dir}/", shell=True)

def setup_images():
    # Copy images
    subprocess.run(f"mkdir -p {image_dir}", shell=True)

    images = []

    # Nested images need to get moved and renamed
    for src in glob.glob("images/*/*"):
        dir_src = os.path.join(dirname, src)
        if os.path.isfile(src):
            filename = os.path.basename(dir_src)
            dst = os.path.join(image_dir, filename)
            subprocess.run(f"cp {dir_src} {dst}", shell=True)

            rel_link = f"images/{filename}"
            images.append(rel_link)

            link_replace[f"/{src}"] = rel_link

    for src in glob.glob("images/*"):
        dir_src = os.path.join(dirname, src)
        if os.path.isfile(src):
            filename = os.path.basename(dir_src)
            dst = os.path.join(image_dir, filename)
            subprocess.run(f"cp {dir_src} {dst}", shell=True)

            rel_link = f"images/{filename}"
            images.append(rel_link)

            link_replace[f"/{src}"] = rel_link

    return images

def id_ref(link):
    base = os.path.basename(link)
    (name, ext) = os.path.splitext(base)
    return name

def manifest_post_tag(post):
    id = id_ref(post)
    href = id + ".xhtml"
    return f'<item id="{id}" href="{href}" media-type="application/xhtml+xml" />'

def spine_toc_post(post):
    id = id_ref(post)
    return f'<itemref idref="{id}" />'

def manifest_img_tag(img):
    base = os.path.basename(img)
    (name, ext) = os.path.splitext(base)

    # FIXME only png is officially supported?
    if ext == ".png":
        t = "png"
    elif ext == ".svg":
        t = "svg"
    elif ext == ".jpg":
        t = "jpg"
    elif ext == ".gif":
        t = "gif"
    else:
        sys.exit("unknown image: " + ext)

    return f'<item id="{name}" href="{img}" media-type="image/{t}" />'

def setup_content_opf(images):
    with open(f"{ebook_files_dir}/content.opf", 'r') as f:
        data = f.read()

    data = data.replace("◊UUID", uuid)

    # ◊MANIFEST_POSTS_TAG
    # <item id="chapter02" href="chap02.xhtml" media-type="application/xhtml+xml" />
    manifest_posts = ('\n' + ' ' * 8).join([manifest_post_tag(post) for post in toc])
    data = data.replace("◊MANIFEST_POSTS_TAG", manifest_posts)

    # ◊MANIFEST_IMG_TAG
    # <item id="imgl" href="images/sample.png" media-type="image/png" />
    manifest_imgs = ('\n' + ' ' * 8).join([manifest_img_tag(img) for img in images])
    data = data.replace("◊MANIFEST_IMG_TAG", manifest_imgs)

    # ◊SPINE_TOC
    # <itemref idref="chapter01" />
    spine_toc = ('\n' + ' ' * 8).join([spine_toc_post(post) for post in toc])
    data = data.replace("◊SPINE_TOC", spine_toc)

    with open(f"{oebps_dir}/content.opf", 'w') as f:
        f.write(data)

def post_title(post):
    return titles[post]

def toc_ncx_post(i, post):
    order = i + 1
    id = id_ref(post)
    href = id + ".xhtml"
    title = post_title(post)
    return f"""<navPoint id="{id}" playOrder="{order}">
        <navLabel>
            <text>{title}</text>
        </navLabel>
        <content src="{href}"/>
    </navPoint>"""

def setup_toc_ncx():
    navpoints = ('\n' + ' ' * 4).join(
            [toc_ncx_post(i, post) for (i, post) in enumerate(toc)])
    data = f"""<?xml version="1.0" encoding="UTF-8"?>
<ncx xmlns="http://www.daisy.org/z3986/2005/ncx/" version="2005-1">

  <head>
    <meta name="dtb:uid" content="{uuid}"/>
    <meta name="dtb:depth" content="1"/>
    <meta name="dtb:totalPageCount" content="0"/>
    <meta name="dtb:maxPageNumber" content="0"/>
  </head>

  <docTitle>
    <text>Why cryptocurrencies?</text>
  </docTitle>

  <navMap>
    {navpoints}
  </navMap>
</ncx>"""

    with open(f"{oebps_dir}/toc.ncx", 'w') as f:
        f.write(data)

def setup_css():
    # FIXME custom stylesheet for epub
    subprocess.run(f"sassc sass/main.scss --style compressed > {oebps_dir}/stylesheet.css", shell=True)

def setup_post_replacements():
    for post in toc:
        (name, ext) = os.path.splitext(post)
        dst = f'{name}.xhtml'
        link_replace[post] = dst

def setup_posts():
    for post in toc:
        setup_post(post)

def setup_post(post):
    (name, ext) = os.path.splitext(post)
    dst = f'{oebps_dir}/{name}.xhtml'
    with open(post, 'r') as f:
        data = f.read()

    for link, new_link in link_replace.items():
        data = data.replace(link, new_link)

    with open(dst, 'w') as f:
        f.write(data)

def create_zip():
    os.chdir(ebook_dir)
    subprocess.run(f'zip -X0 why_cryptocurrencies.epub mimetype', shell=True)
    subprocess.run(f'zip -Xur9D why_cryptocurrencies.epub *', shell=True)

if __name__ == '__main__':
    main()

